version: "3.9"
services:
  main:
    build: .
    command: ["air"]
    ports:
      - 9060:9090
    restart: always
    environment:
      ADDR: :9090
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_NAME: datastore
      FILE_BASE_PATH: ./static/images
      FILE_MAX_SIZE: 5242880 # 5MB
    volumes:
      - .:/app
    networks:
      - boilerplate

networks:
  boilerplate:
    name: boilerplate_net
